### ISSUE TITLE
How do i fix this 

### ISSUE THREAD

**Issue by JohnKinyanjui** [YeMyoAung/starlight_epub_viewer#3]
android:exported needs to be explicitly specified for element <activity#com.folioreader.ui.activity.SearchActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : android:exported needs to be explicitly specified for element <activity#com.folioreader.ui.activity.SearchActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by YeMyoAung** [comment]
If you facing with this error, make sure your repo is up to date.
if you not sure flutter pub upgrade & retry it.
If not solve your problem try these step

1.  add android:exported=true in androidmanifest.xml.

another way

Backup Android folder & reinit Android & add android:exported=true in androidmanifest.xml.
